# Generated by Django 4.2.29 on 2026-04-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosks', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_kiosks',
            field=models.ManyToManyField(blank=True, help_text='Kiosks this supervisor is responsible for monitoring.', related_name='assigned_supervisors', to='kiosks.kiosk'),
        ),
    ]
