# Generated by Django 4.2.29 on 2026-04-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='opening_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
