# Generated by Django 5.2.10 on 2026-04-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_opening_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='closing_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Shift Report'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='opening_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Report Generator (Main Photo)'),
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reports/extra/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_photos', to='reports.dailyreport')),
            ],
        ),
    ]
