# Generated by Django 5.2.10 on 2026-04-13 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorvisit',
            name='attendance_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visits/'),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='attendance_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='cleanliness_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visits/'),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='cleanliness_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='customer_service_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visits/'),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='customer_service_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='device_care_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visits/'),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='device_care_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='marketing_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visits/'),
        ),
        migrations.AddField(
            model_name='supervisorvisit',
            name='marketing_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
