# Generated by Django 5.2.10 on 2026-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='cashier_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sales/cashier/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='starting_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
